-- Paquete para generación de reportes y análisis
-- Proyecto: Sistema de Gestión de Viajes Uber
-- Funcionalidades:
--   - Análisis de demanda por hora/día/mes
--   - Top rutas más frecuentes
--   - Ingresos por método de pago
--   - Tasa de cancelación por razón
--   - Conductores más eficientes
--   - Análisis de ratings
--   - Métricas de tiempo promedio (VTAT, CTAT)

